# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
BOX_IMAGE = "centos/7"
NODE_COUNT = 2
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = BOX_IMAGE
  config.vm.provider :virtualbox do |virtualbox, override|
    virtualbox.customize ["modifyvm", :id, "--memory", 2048]
  end
  
  config.vm.provider :lxc do |lxc, override|
    override.vm.box = "visibilityspots/centos-7.x-minimal"
  end

  config.vm.define "nomadserver" do |server|
    server.vm.hostname = "server"
    server.vm.network :private_network, ip: "10.0.0.10", virtualbox__intnet: true, auto_config: true
	server.vm.provision "ansible" do |ansible|
      ansible.config_file = "ansible/ansible.cfg"
      ansible.playbook = "ansible/plays/playbook.yml"
      ansible.groups = {
        "servers" => ["server"]
      }
      ansible.verbose = '-vvv'
    end
	#nomadserver.vm.provision "file", source: "webserver.hcl", destination: "~/webserver.hcl"
	end
  
  (1..NODE_COUNT).each do |i|
     config.vm.define "agent#{i}" do |subconfig|
       subconfig.vm.box = BOX_IMAGE
       subconfig.vm.hostname = "AGENT#{i}"
       subconfig.vm.network :private_network, ip: "10.0.0.#{i + 10}", virtualbox__intnet: true, auto_config: true
	   subconfig.vm.provision "ansible" do |ansible|
       ansible.config_file = "ansible/ansible.cfg"
       ansible.playbook = "ansible/plays/playbook.yml"
       ansible.groups = {
         "clients" => ["AGENT1","AGENT2"]
       }
       ansible.verbose = '-vvv'
	   end   
	 end
   end 
end
